{
  "props": {
    "singleton": false
  },
  "components": {
    "Downloader": {
      "type": "bundle\\http\\HttpDownloader",
      "x": 320,
      "y": 144,
      "props": {
        "useTempFile": true,
        "threadCount": 4,
        "breakOnError": true
      }
    },
    "Load_Table": {
      "type": "script\\MacroScript",
      "x": 128,
      "y": 112,
      "props": {
        "disabled": false,
        "runOnApply": false,
        "runOnce": false
      }
    },
    "dirChooser": {
      "type": "script\\DirectoryChooserScript",
      "x": 224,
      "y": 112,
      "props": {
        "inputNode": "",
        "actionNode": ""
      }
    },
    "ini": {
      "type": "script\\storage\\IniStorage",
      "x": 32,
      "y": 112,
      "props": {
        "path": "config.ini",
        "autoSave": "1",
        "trimValues": true,
        "multiLineValues": "1"
      }
    },
    "ForceDownloader": {
      "type": "bundle\\http\\HttpDownloader",
      "x": 320,
      "y": 80,
      "props": {
        "useTempFile": true,
        "threadCount": 1,
        "breakOnError": true
      }
    }
  }
}